EducApp/config/routes.rb
Rails.application.routes.draw do
  resources :disciplinas
  resources :alunos
  resources :professors
  resources :professors
  resources :turmas
  resources :cursos
  resources :escolas

end

EducApp/app/models/turma.rb
class Turma < ActiveRecord::Base
end

EducApp/app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turma_params
      params.require(:turma).permit(:nome, :curso_id, :reference)
    end
end

EducApp/app/helpers/turmas_helper.rb
module TurmasHelper
end

EducApp/app/views/turmas/_form.html.erb
<%= form_for(@turma) do |f| %>
  <% if @turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% @turma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :curso_id %><br>
    <%= f.number_field :curso_id %>
  </div>
  <div class="field">
    <%= f.label :reference %><br>
    <%= f.text_field :reference %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

EducApp/app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form' %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

EducApp/app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Curso</th>
      <th>Reference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.nome %></td>
        <td><%= turma.curso_id %></td>
        <td><%= turma.reference %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turma', new_turma_path %>

EducApp/app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form' %>

<%= link_to 'Back', turmas_path %>

EducApp/app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @turma.nome %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @turma.curso_id %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @turma.reference %>
</p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>